name: Node.js CI

on: [push]

env:
  GIT_USERNAME: ${{ secrets.GIT_USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - run: |      
          git config --global user.email $GIT_USERNAME;
          git config --global user.name "GithubPages";
      - run: npm install
      - run: npm run deploy
